ci:
  - changed-files:
    - any-glob-to-any-file: .github/**
test:
  - changed-files:
    - any-glob-to-any-file: fuzz/**
    - any-glob-to-any-file: '*/tests/**'
doc:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
