// SPDX-License-Identifier: CC0-1.0

//! Test that all public types and modules from bitcoin_units are re-exported in bitcoin_primitives.
//!
//! This test is automatically generated by contrib/generate-re-export-test.sh
//! Any compilation error indicates a missing re-export.

#![allow(dead_code)]
#![allow(unused_imports)]
// No benefit in running this test without features enabled.
#![cfg(feature = "alloc")]
#![cfg(feature = "hex")]
#![cfg(feature = "arbitrary")]

#[test]
fn check_all_bitcoin_units_items_are_reexported() {
    // This test will fail to compile if any bitcoin_units item is not re-exported in bitcoin_primitives
    
    use bitcoin_primitives::absolute as _;
    use bitcoin_primitives::absolute::ConversionError as _;
    use bitcoin_primitives::absolute::error as _;
    use bitcoin_primitives::absolute::error::ConversionError as _;
    use bitcoin_primitives::absolute::error::IncompatibleHeightError as _;
    use bitcoin_primitives::absolute::error::IncompatibleTimeError as _;
    use bitcoin_primitives::absolute::error::ParseHeightError as _;
    use bitcoin_primitives::absolute::error::ParseTimeError as _;
    use bitcoin_primitives::absolute::Height as _;
    use bitcoin_primitives::absolute::IncompatibleHeightError as _;
    use bitcoin_primitives::absolute::IncompatibleTimeError as _;
    use bitcoin_primitives::absolute::LockTime as _;
    use bitcoin_primitives::absolute::MedianTimePast as _;
    use bitcoin_primitives::absolute::ParseHeightError as _;
    use bitcoin_primitives::absolute::ParseTimeError as _;
    use bitcoin_primitives::amount::Amount as _;
    use bitcoin_primitives::amount as _;
    use bitcoin_primitives::Amount as _;
    use bitcoin_primitives::amount::Denomination as _;
    use bitcoin_primitives::amount::Display as _;
    use bitcoin_primitives::amount::error as _;
    use bitcoin_primitives::amount::error::InputTooLargeError as _;
    use bitcoin_primitives::amount::error::InvalidCharacterError as _;
    use bitcoin_primitives::amount::error::MissingDenominationError as _;
    use bitcoin_primitives::amount::error::MissingDigitsError as _;
    use bitcoin_primitives::amount::error::OutOfRangeError as _;
    use bitcoin_primitives::amount::error::ParseAmountError as _;
    use bitcoin_primitives::amount::error::ParseDenominationError as _;
    use bitcoin_primitives::amount::error::ParseError as _;
    use bitcoin_primitives::amount::error::PossiblyConfusingDenominationError as _;
    use bitcoin_primitives::amount::error::TooPreciseError as _;
    use bitcoin_primitives::amount::error::UnknownDenominationError as _;
    use bitcoin_primitives::amount::OutOfRangeError as _;
    use bitcoin_primitives::amount::ParseAmountError as _;
    use bitcoin_primitives::amount::ParseDenominationError as _;
    use bitcoin_primitives::amount::ParseError as _;
    use bitcoin_primitives::amount::serde as _;
    use bitcoin_primitives::amount::serde::as_btc as _;
    use bitcoin_primitives::amount::serde::as_btc::opt as _;
    use bitcoin_primitives::amount::serde::as_sat as _;
    use bitcoin_primitives::amount::serde::as_sat::opt as _;
    use bitcoin_primitives::amount::serde::as_str as _;
    use bitcoin_primitives::amount::serde::as_str::opt as _;
    use bitcoin_primitives::amount::SignedAmount as _;
    use bitcoin_primitives::block as _;
    use bitcoin_primitives::block::BlockHeight as _;
    use bitcoin_primitives::block::BlockHeightInterval as _;
    use bitcoin_primitives::block::BlockMtp as _;
    use bitcoin_primitives::block::BlockMtpInterval as _;
    use bitcoin_primitives::BlockHeight as _;
    use bitcoin_primitives::BlockHeightInterval as _;
    use bitcoin_primitives::BlockMtp as _;
    use bitcoin_primitives::BlockMtpInterval as _;
    use bitcoin_primitives::BlockTime as _;
    use bitcoin_primitives::block::TooBigForRelativeHeightError as _;
    use bitcoin_primitives::fee_rate as _;
    use bitcoin_primitives::FeeRate as _;
    use bitcoin_primitives::fee_rate::FeeRate as _;
    use bitcoin_primitives::fee_rate::serde as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_kwu_floor as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_kwu_floor::opt as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_vb_ceil as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_vb_ceil::opt as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_vb_floor as _;
    use bitcoin_primitives::fee_rate::serde::as_sat_per_vb_floor::opt as _;
    use bitcoin_primitives::fee_rate::serde::OverflowError as _;
    use bitcoin_primitives::locktime::absolute as _;
    use bitcoin_primitives::locktime::absolute::ConversionError as _;
    use bitcoin_primitives::locktime::absolute::error as _;
    use bitcoin_primitives::locktime::absolute::error::ConversionError as _;
    use bitcoin_primitives::locktime::absolute::error::IncompatibleHeightError as _;
    use bitcoin_primitives::locktime::absolute::error::IncompatibleTimeError as _;
    use bitcoin_primitives::locktime::absolute::error::ParseHeightError as _;
    use bitcoin_primitives::locktime::absolute::error::ParseTimeError as _;
    use bitcoin_primitives::locktime::absolute::Height as _;
    use bitcoin_primitives::locktime::absolute::IncompatibleHeightError as _;
    use bitcoin_primitives::locktime::absolute::IncompatibleTimeError as _;
    use bitcoin_primitives::locktime::absolute::LockTime as _;
    use bitcoin_primitives::locktime::absolute::MedianTimePast as _;
    use bitcoin_primitives::locktime::absolute::ParseHeightError as _;
    use bitcoin_primitives::locktime::absolute::ParseTimeError as _;
    use bitcoin_primitives::locktime as _;
    use bitcoin_primitives::locktime::relative as _;
    use bitcoin_primitives::locktime::relative::DisabledLockTimeError as _;
    use bitcoin_primitives::locktime::relative::error as _;
    use bitcoin_primitives::locktime::relative::error::DisabledLockTimeError as _;
    use bitcoin_primitives::locktime::relative::error::InvalidHeightError as _;
    use bitcoin_primitives::locktime::relative::error::InvalidTimeError as _;
    use bitcoin_primitives::locktime::relative::error::IsSatisfiedByError as _;
    use bitcoin_primitives::locktime::relative::error::IsSatisfiedByHeightError as _;
    use bitcoin_primitives::locktime::relative::error::IsSatisfiedByTimeError as _;
    use bitcoin_primitives::locktime::relative::error::TimeOverflowError as _;
    use bitcoin_primitives::locktime::relative::InvalidHeightError as _;
    use bitcoin_primitives::locktime::relative::InvalidTimeError as _;
    use bitcoin_primitives::locktime::relative::IsSatisfiedByError as _;
    use bitcoin_primitives::locktime::relative::IsSatisfiedByHeightError as _;
    use bitcoin_primitives::locktime::relative::IsSatisfiedByTimeError as _;
    use bitcoin_primitives::locktime::relative::LockTime as _;
    use bitcoin_primitives::locktime::relative::NumberOf512Seconds as _;
    use bitcoin_primitives::locktime::relative::NumberOfBlocks as _;
    use bitcoin_primitives::locktime::relative::TimeOverflowError as _;
    use bitcoin_primitives::NumOpResult as _;
    use bitcoin_primitives::parse as _;
    use bitcoin_primitives::parse::ParseIntError as _;
    use bitcoin_primitives::parse::PrefixedHexError as _;
    use bitcoin_primitives::parse::UnprefixedHexError as _;
    use bitcoin_primitives::relative as _;
    use bitcoin_primitives::relative::DisabledLockTimeError as _;
    use bitcoin_primitives::relative::error as _;
    use bitcoin_primitives::relative::error::DisabledLockTimeError as _;
    use bitcoin_primitives::relative::error::InvalidHeightError as _;
    use bitcoin_primitives::relative::error::InvalidTimeError as _;
    use bitcoin_primitives::relative::error::IsSatisfiedByError as _;
    use bitcoin_primitives::relative::error::IsSatisfiedByHeightError as _;
    use bitcoin_primitives::relative::error::IsSatisfiedByTimeError as _;
    use bitcoin_primitives::relative::error::TimeOverflowError as _;
    use bitcoin_primitives::relative::InvalidHeightError as _;
    use bitcoin_primitives::relative::InvalidTimeError as _;
    use bitcoin_primitives::relative::IsSatisfiedByError as _;
    use bitcoin_primitives::relative::IsSatisfiedByHeightError as _;
    use bitcoin_primitives::relative::IsSatisfiedByTimeError as _;
    use bitcoin_primitives::relative::LockTime as _;
    use bitcoin_primitives::relative::NumberOf512Seconds as _;
    use bitcoin_primitives::relative::NumberOfBlocks as _;
    use bitcoin_primitives::relative::TimeOverflowError as _;
    use bitcoin_primitives::result as _;
    use bitcoin_primitives::result::MathOp as _;
    use bitcoin_primitives::result::NumOpError as _;
    use bitcoin_primitives::result::NumOpResult as _;
    use bitcoin_primitives::sequence as _;
    use bitcoin_primitives::Sequence as _;
    use bitcoin_primitives::sequence::Sequence as _;
    use bitcoin_primitives::SignedAmount as _;
    use bitcoin_primitives::time as _;
    use bitcoin_primitives::time::BlockTime as _;
    use bitcoin_primitives::weight as _;
    use bitcoin_primitives::Weight as _;
    use bitcoin_primitives::weight::Weight as _;
}
