[package]
name = "bitcoin-bip158"
version = "0.0.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
repository = "https://github.com/rust-bitcoin/rust-bitcoin"
homepage = "https://rust-bitcoin.org"
description = "Golomb-rice coded filters for set membership query."
categories = ["cryptography::cryptocurrencies"]
keywords = ["bitcoin", "peer-to-peer", "cryptography"]
readme = "README.md"
edition = "2021"
rust-version = "1.74.0"
exclude = ["tests", "contrib"]

[features]
default = ["std", "hex"]
std = ["alloc", "encoding/std", "hashes/std", "internals/std"]
alloc = ["encoding/alloc", "hashes/alloc", "internals/alloc"]
serde = ["hashes/serde", "alloc", "hex"]
hex = ["hashes/hex"]

[dependencies]
encoding = { package = "bitcoin-consensus-encoding", path = "../consensus_encoding", version = "1.2.0", default-features = false }
hashes = { package = "bitcoin_hashes", path = "../hashes", version = "1.2.0", default-features = false }
internals = { package = "bitcoin-internals", path = "../internals", version = "0.6.0" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
