name: Nightly rustfmt
on:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
  workflow_dispatch: # allows manual triggering
permissions: {}
jobs:
  format:
    name: Nightly rustfmt
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: Run Nightly rustfmt
        run: cargo rbmt fmt
      - name: Get the current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          author: Fmt Bot <bot@example.com>
          title: Automated nightly rustfmt (${{ env.date }})
          body: |
           Automated nightly `rustfmt` changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          commit-message: ${{ env.date }} automated rustfmt nightly
          labels: rustfmt
