# Fuzz targets are distributed over a static number of jobs.

name: Fuzz
on:
  schedule:
    # 5am every day UTC, this correlates to:
    # - 10pm PDT
    # - 6am CET
    # - 4pm AEDT
    - cron: '00 05 * * *'
permissions: {}

jobs:
  fuzz:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        shard_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    steps:
      - name: Install test dependencies
        run: sudo apt-get update -y && sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc libiberty-dev
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache-fuzz
        with:
          path: |
            ~/.cargo/bin
            fuzz/target
            target
          key: cache-fuzz-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
        with:
          toolchain: '1.74.0'
      - run: cargo install --locked --version 0.12.0 cargo-fuzz
      - name: Fuzz shard ${{ matrix.shard_id }}
        run: |
          shard_targets=($(cargo fuzz list | sort | awk -v shard=${{ matrix.shard_id }} 'BEGIN{i=0} {if (i++ % 16 == shard) print}'))
          for target in "${shard_targets[@]}"; do
            if [[ "$target" =~ ^bitcoin ]]; then
              export RUSTFLAGS='--cfg=hashes_fuzz --cfg=secp256k1_fuzz'
            else
              unset RUSTFLAGS
            fi
            echo "Using RUSTFLAGS: ${RUSTFLAGS:-<empty>}"
            cd fuzz && ./fuzz.sh "$target"
            cd ..
          done
