name: Miri
on:   # yamllint disable-line rule:truthy
  schedule:
    # 10am every day UTC, this correlates to:
    # - 3am PDT
    # - 11am CET
    # - 9pm AEDT
    - cron: '00 10 * * *'

permissions: {}

jobs:
  Miri:
    name: Miri
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Read nightly version"
        id: read_toolchain
        run: echo "nightly_version=$(cargo metadata --format-version 1 | jq -r '.metadata.rbmt.toolchains.nightly')" >> $GITHUB_OUTPUT
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ steps.read_toolchain.outputs.nightly_version }}
          components: miri
      - name: "Setup miri"
        run: cargo miri setup
      - name: "Set dependencies"
        run: cp Cargo-recent.lock Cargo.lock
      - name: "Run test script"
        run: ./contrib/test-miri.sh
