name: Manage PR
on:
  - pull_request_target # zizmor: ignore[dangerous-triggers]
permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout master
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Generate label config
        run: ./.github/gen_label_config.sh
      - name: Update labels
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
