name: Manage PR
on:
  - pull_request_target # zizmor: ignore[dangerous-triggers]
permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout master
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: master
          persist-credentials: false
      - name: Checkout merge commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: merge
          ref: "refs/pull/${{ github.event.number }}/merge"
          persist-credentials: false
      - name: Generate label config
        run: cd master && SCAN_DIR=../merge ./contrib/gen_label_config.sh
      - name: Update labels
        uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          configuration-path: master/.github/labeler.yml
          sync-labels: true
