name: Mayhem
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DESERIALIZE_ADDRESS_MAYHEMFILE: mayhem/deserialize_address.mayhemfile
  DESERIALIZE_BLOCK_MAYHEMFILE: mayhem/deserialize_block.mayhemfile
  DESERIALIZE_SCRIPT_MAYHEMFILE: mayhem/deserialize_script.mayhemfile
  DESERIALIZE_TRANSACTION_MAYHEMFILE: mayhem/deserialize_transaction.mayhemfile

jobs:
  build:
    name: "${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Start analysis for deserialize_address
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DESERIALIZE_ADDRESS_MAYHEMFILE }} --duration 300
          sarif-output: sarif

      - name: Start analysis for deserialize_block
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DESERIALIZE_BLOCK_MAYHEMFILE }} --duration 300
          sarif-output: sarif

      - name: Start analysis for deserialize_script
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DESERIALIZE_SCRIPT_MAYHEMFILE }} --duration 300
          sarif-output: sarif

      - name: Start analysis for deserialize_transaction
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ steps.meta.outputs.tags }} --file ${{ env.DESERIALIZE_TRANSACTION_MAYHEMFILE }} --duration 300
          sarif-output: sarif

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif