--- # rust-bitcoin CI: If you edit this file please update README.md
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - 0.31.x
      - "test-ci/**"
  pull_request:

name: Continuous integration

permissions: {}

env:
  RBMT_LOG_LEVEL: "progress"

jobs:
  Test:
    name: Test - ${{ matrix.toolchain }} toolchain, ${{ matrix.dep }} deps
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, msrv]
        dep: [minimal, recent]
        # The 1.48 MSRV cargo cannot resolve the recent lockfile.
        exclude:
          - toolchain: msrv
            dep: recent
    steps:
      # Cleaning up github bloat so that test feature artifacts don't run out of disk.
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Run tests"
        # excluded fuzz because honggfuzz dependency can't be built on 1.48 MSRV.
        run: cargo rbmt test --toolchain ${{ matrix.toolchain }} --lock-file ${{ matrix.dep }} -p bitcoin -p hashes -p internals

  Check:
    name: Check - ${{ matrix.task }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        task: [api, lint, docs, docsrs, bench]
    steps:
      # Cleaning up github bloat so that test feature artifacts don't run out of disk.
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Run ${{ matrix.task }}"
        run: cargo rbmt ${{ matrix.task }}

  Kani:
    name: Kani codegen - stable toolchain
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Set dependencies"
        run: cp Cargo-recent.lock Cargo.lock
      - name: "Build Kani proofs"
        uses: model-checking/kani-github-action@f838096619a707b0f6b2118cf435eaccfa33e51f # v1.1
        with:
          args: "--only-codegen"

  Prepare:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      nightly_version: ${{ steps.read_toolchain.outputs.nightly_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Read workspace versions"
        id: read_toolchain
        run: echo "nightly_version=$(cargo metadata --format-version 1 --no-deps | jq -r '.metadata.rbmt.toolchains.nightly')" >> $GITHUB_OUTPUT

  Arch32bit:
    name: Test 32-bit version
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: "Add architecture i386 and install dependencies"
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y \
            gcc-multilib \
            g++-multilib \
            libc6-dev-i386 \
            lib32stdc++-13-dev
      - name: "Install target"
        run: rustup target add i686-unknown-linux-gnu
      - name: "Set dependencies"
        run: cp Cargo-recent.lock Cargo.lock
      - name: "Run test on i686"
        run: cargo test --target i686-unknown-linux-gnu

  Cross:
    name: Cross test - stable toolchain
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target:
          - s390x-unknown-linux-gnu
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: "Install target"
        run: rustup target add ${{ matrix.target }}
      - name: "Install cross"
        run: cargo install cross --locked
      - name: "Set dependencies"
        run: cp Cargo-recent.lock Cargo.lock
      - name: "Run cross test"
        run: cross test --target ${{ matrix.target }}

  Embedded:
    name: Embedded - nightly toolchain
    needs: Prepare
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      RUSTFLAGS: "-C link-arg=-Tlink.x"
      CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Set up QEMU"
        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ needs.Prepare.outputs.nightly_version }}
          targets: thumbv7m-none-eabi
      - name: "Install rust-src"
        run: rustup component add rust-src
      - name: "Run bitcoin/embedded"
        run: cd bitcoin/embedded && cp Cargo-recent.lock Cargo.lock && cargo run --target thumbv7m-none-eabi
      - name: "Run hashes/embedded no alloc"
        run: cd hashes/embedded && cp Cargo-recent.lock Cargo.lock && cargo run --target thumbv7m-none-eabi
      - name: "Run hashes/embedded with alloc"
        run: cd hashes/embedded && cp Cargo-recent.lock Cargo.lock && cargo run --target thumbv7m-none-eabi --features=alloc

  ASAN: # hashes crate only.
    name: ASAN - nightly toolchain
    needs: Prepare
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        dep: [recent]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: ${{ needs.Prepare.outputs.nightly_version }}
      - name: "Install rust-src"
        run: rustup component add rust-src
      - name: "Set dependencies"
        run: cp Cargo-${{ matrix.dep }}.lock Cargo.lock
      - name: "Run address and memory sanitizers"
        working-directory: hashes
        env:
          FEATURES: "serde serde-std std alloc"
        run: |
          set -euxo pipefail
          cargo clean
          CC='clang -fsanitize=address -fno-omit-frame-pointer' \
            RUSTFLAGS='-Zsanitizer=address -Clinker=clang -Cforce-frame-pointers=yes' \
            ASAN_OPTIONS='detect_leaks=1 detect_invalid_pointer_pairs=1 detect_stack_use_after_return=1' \
            cargo test --lib --no-default-features --features="$FEATURES" -Zbuild-std --target x86_64-unknown-linux-gnu
          cargo clean
          CC='clang -fsanitize=memory -fno-omit-frame-pointer' \
            RUSTFLAGS='-Zsanitizer=memory -Zsanitizer-memory-track-origins -Cforce-frame-pointers=yes' \
            cargo test --lib --no-default-features --features="$FEATURES" -Zbuild-std --target x86_64-unknown-linux-gnu

  WASM:
    name: WebAssembly Build # hashes crate only.
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Crate
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: "Set dependencies"
        run: cp Cargo-recent.lock Cargo.lock
      - name: Running WASM build
        working-directory: hashes
        run: |
          set -euxo pipefail
          clang --version
          CARGO_TARGET_DIR=wasm cargo install --force wasm-pack
          printf '\n[target.wasm32-unknown-unknown.dev-dependencies]\nwasm-bindgen-test = "0.3"\n' >> Cargo.toml
          printf '\n[lib]\ncrate-type = ["cdylib", "rlib"]\n' >> Cargo.toml
          CC=clang-9 wasm-pack build
          CC=clang-9 wasm-pack test --node
