# The workflow detects semver breaks and uploads an artifact
# for another job to use to add labels to the relevant PR. This
# is following security best practices: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

on:   # yamllint disable-line rule:truthy
  pull_request:

# This key is what connects the job output to the labeller followup.
name: Check semver breaks
permissions: {}

jobs:
  Semver:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # we need full history for cargo semver-checks
          persist-credentials: false
      - name: "Install Rustup"
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # v1
        with:
          toolchain: stable
      - name: "Select stable-version"
        run: |
          rustup default $(cargo metadata --format-version 1 | jq -r '.metadata.rbmt.toolchains.stable')
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4 # v1.21.0
      - name: "Binstall pinned cargo-semver-checks"
        run: cargo binstall cargo-semver-checks@$(cat ./.github/workflows/cargo-semver-checks-version) --no-confirm
      - name: "Run semver checks"
        id: semver
        run: |
          set +e
          ./contrib/check-semver.sh ${{ github.event.pull_request.base.sha || github.event.before }}
          echo "exit_code=$?" >> $GITHUB_OUTPUT
      - name: "Save breaking state"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          EXIT_CODE: ${{ steps.semver.outputs.exit_code }}
        run: |
          echo "$PR_NUMBER" > semver-break
          echo "$EXIT_CODE" >> semver-break
      - name: "Upload breaking state"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: semver-break
          path: semver-break
      - name: "Fail on breaks to stable packages"
        if: ${{ steps.semver.outputs.exit_code == 1 }}
        run: exit 1
