on:   # yamllint disable-line rule:truthy
  pull_request:

name: Check semver breaks
permissions: {}

jobs:
  PR:
    name: PR Semver - stable toolchain
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # we need full history for cargo semver-checks
          persist-credentials: false
      - name: "Install Rustup"
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: "Select stable-version"
        run: |
          rustup default $(cargo metadata --format-version 1 | jq -r '.metadata.rbmt.toolchains.stable')
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@aaa84a43aec4955a42c5ffc65d258961e39f276e # v1.19.1
      - name: "Binstall pinned cargo-semver-checks"
        run: cargo binstall cargo-semver-checks@$(cat ./.github/workflows/cargo-semver-checks-version) --no-confirm
      - name: "Run semver checker script"
        run: ./contrib/check-semver-pr.sh
      - name: Save PR number
        if: ${{ hashFiles('semver-break') != '' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # check if PR_NUMBER is a number
          if ! [[ "$PR_NUMBER" =~ ^-?[0-9]+$ ]]; then
              echo "$PR_NUMBER is not a number."
              exit 1
          fi
          echo "$PR_NUMBER" > ./semver-break
      - name: "Save breaking state"
        if: ${{ hashFiles('semver-break') != '' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: semver-break
          path: semver-break

  Feature:
    name: Non additive cargo features - stable toolchain
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install Rustup"
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      - name: "Select stable-version"
        run: |
          rustup default $(cargo metadata --format-version 1 | jq -r '.metadata.rbmt.toolchains.stable')
      - name: "Install cargo-binstall"
        uses: cargo-bins/cargo-binstall@aaa84a43aec4955a42c5ffc65d258961e39f276e # v1.19.1
      - name: "Binstall pinned cargo-semver-checks"
        run: cargo binstall cargo-semver-checks@$(cat ./.github/workflows/cargo-semver-checks-version) --no-confirm
      - name: "Run semver checker script"
        run: ./contrib/check-semver-feature.sh

