name: Shellcheck
on:
  pull_request:
    branches:
      - master
permissions: {}
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      env:
        SHELLCHECK_OPTS: -x # allow outside sources
