name: GitHub Actions Security Analysis with zizmor 🌈

on:
  pull_request:
    branches: ["**"]
    paths:
      - '.github/**'

permissions: {}

jobs:
  zizmor:
    name: zizmor via PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v5

      - name: Run zizmor 🌈
        run: uvx zizmor@1.22.0 .
