name: GitHub Actions Security Analysis with zizmor 🌈

on:
  pull_request:
    branches: ["**"]
    paths:
      - '.github/**'

permissions: {}

jobs:
  zizmor:
    name: zizmor via PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v5

      - name: Run zizmor 🌈
        run: uvx zizmor@1.22.0 .
